# Generated by Django 4.1.3 on 2022-12-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('area_delivery_charges', models.IntegerField()),
            ],
            options={
                'db_table': 'area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('idcity', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('idrestaurant', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=45)),
                ('restaurant_email', models.CharField(max_length=45)),
                ('restaurant_phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('restaurant_description', models.CharField(max_length=200)),
                ('area_pincode', models.ForeignKey(db_column='area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.area')),
            ],
            options={
                'db_table': 'restaurant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=45)),
                ('user_mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user_sec_question', models.CharField(max_length=60)),
                ('user_sec_answer', models.CharField(max_length=60)),
                ('user_image', models.ImageField(null=True, upload_to='myImages/')),
                ('is_admin', models.IntegerField()),
                ('area_pincode', models.ForeignKey(db_column='area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.area')),
                ('restaurant_idrestaurant', models.ForeignKey(db_column='restaurant_idrestaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.restaurant')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city_idcity',
            field=models.ForeignKey(db_column='city_idcity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.city'),
        ),
    ]
