# Generated by Django 4.1.3 on 2022-12-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city_idcity',
            field=models.ForeignKey(db_column='city_idcity', null=True, on_delete=django.db.models.deletion.PROTECT, to='Brewer_Cafe_And_Restro.city'),
        ),
    ]
