# Generated by Django 4.1.3 on 2022-12-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0004_alter_area_city_idcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_pincode',
            field=models.ForeignKey(db_column='area_pincode', default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.area'),
        ),
    ]
