# Generated by Django 4.1.3 on 2022-12-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0005_alter_user_area_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='', null=True, upload_to='myImages/'),
        ),
    ]
