# Generated by Django 4.1.3 on 2022-12-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0008_rename_restaurant_idrestaurant_user_idrestaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mobile',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
