# Generated by Django 4.1.3 on 2022-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0017_alter_user_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sec_answer',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_sec_question',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
