# Generated by Django 4.1.3 on 2022-12-20 08:01

import Brewer_Cafe_And_Restro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0025_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=Brewer_Cafe_And_Restro.models.filepath),
        ),
    ]
