# Generated by Django 4.1.3 on 2022-12-20 10:43

import Brewer_Cafe_And_Restro.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0026_alter_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('iditem_category', models.AutoField(primary_key=True, serialize=False)),
                ('item_category_name', models.CharField(max_length=60)),
                ('item_category_description', models.CharField(max_length=200)),
                ('item_category_image', models.ImageField(blank=True, null=True, upload_to=Brewer_Cafe_And_Restro.models.filepathItemCategory)),
                ('restaurant_idrestaurant', models.ForeignKey(db_column='restaurant_idrestaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.restaurant')),
            ],
            options={
                'db_table': 'item_category',
                'managed': True,
            },
        ),
    ]
