# Generated by Django 4.1.3 on 2023-01-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0029_offer_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_value',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
