# Generated by Django 4.1.3 on 2023-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0030_alter_offer_offer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
