# Generated by Django 4.1.3 on 2023-01-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0031_itemcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='item_category_name',
            new_name='title',
        ),
    ]
