# Generated by Django 4.1.3 on 2023-01-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0032_rename_item_category_name_itemcategory_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='title',
            new_name='item_category_name',
        ),
    ]
