# Generated by Django 4.1.3 on 2023-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0038_order_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderemail',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderfname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderlname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordermobile',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
