# Generated by Django 4.1.3 on 2023-01-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0039_order_orderemail_order_orderfname_order_orderlname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
