# Generated by Django 4.1.3 on 2023-01-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0042_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_value',
            field=models.FloatField(null=True),
        ),
    ]
