# Generated by Django 4.1.3 on 2023-01-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0048_remove_item_offer_record_cart_offer_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='offer_record',
        ),
    ]
