# Generated by Django 4.1.3 on 2023-01-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0050_cart_offer_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
