# Generated by Django 4.1.3 on 2023-01-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0057_alter_cart_offer_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_afterfive',
            field=models.DateField(null=True),
        ),
    ]
