# Generated by Django 4.1.3 on 2023-01-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0058_order_created_afterfive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_afterfive',
        ),
    ]
