# Generated by Django 4.1.3 on 2023-01-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0060_alter_order_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
