# Generated by Django 4.1.3 on 2023-01-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0062_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_iduser',
        ),
    ]
