# Generated by Django 4.1.3 on 2023-01-31 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0063_remove_notification_user_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('idtable', models.AutoField(primary_key=True, serialize=False)),
                ('table_total_empty_table', models.IntegerField()),
                ('total_table_reserved', models.IntegerField()),
                ('table_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'table',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivery_date',
            field=models.DateField(default=datetime.date(2023, 1, 31)),
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('idtable_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('tableResfname', models.CharField(max_length=150, null=True)),
                ('tableReslname', models.CharField(max_length=150, null=True)),
                ('tableResemail', models.CharField(max_length=150, null=True)),
                ('tableResmobile', models.CharField(max_length=150, null=True)),
                ('table_reservation_date', models.DateTimeField(auto_now_add=True)),
                ('table_reservation_time', models.CharField(max_length=45)),
                ('table_reservation_no_guest', models.IntegerField()),
                ('table_reservation_total_table_reserved', models.CharField(max_length=45)),
                ('total_amount', models.FloatField()),
                ('tableRes_payment_method', models.CharField(max_length=150)),
                ('tableRes_payment_id', models.CharField(max_length=250, null=True)),
                ('tableRes_status', models.CharField(default='Success', max_length=150)),
                ('user_iduser', models.ForeignKey(db_column='user_iduser', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.user')),
            ],
            options={
                'db_table': 'table_reservation',
                'managed': True,
            },
        ),
    ]
