# Generated by Django 4.1.3 on 2023-02-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0066_alter_tablereservation_table_reservation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='table_reservation_date',
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='table_reservation_time',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='table_reservation_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
