# Generated by Django 4.1.3 on 2023-02-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0067_remove_tablereservation_table_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
