# Generated by Django 4.1.3 on 2023-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0068_alter_tablereservation_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
