# Generated by Django 4.1.3 on 2023-02-04 18:51

import Brewer_Cafe_And_Restro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0069_alter_tablereservation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to=Brewer_Cafe_And_Restro.models.filepath),
        ),
    ]
