# Generated by Django 4.1.3 on 2023-02-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0070_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
