# Generated by Django 4.1.3 on 2023-02-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0071_restaurant_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cancel_order',
            field=models.IntegerField(null=True),
        ),
    ]
