# Generated by Django 4.1.3 on 2023-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0073_tablereservation_is_table_reservation_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_cancel_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='is_table_reservation_cancel',
            field=models.IntegerField(default=0),
        ),
    ]
