# Generated by Django 4.1.3 on 2023-02-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0074_alter_order_is_cancel_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='total_table',
            field=models.IntegerField(null=True),
        ),
    ]
