# Generated by Django 4.1.3 on 2023-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0076_purchase_purchasereturn_supplier_rawmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_order_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
