# Generated by Django 4.1.3 on 2023-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0078_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
