# Generated by Django 4.1.3 on 2023-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0079_alter_order_cancel_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='gst',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
