# Generated by Django 4.1.3 on 2023-02-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0080_alter_purchase_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_total_empty_table',
        ),
        migrations.RemoveField(
            model_name='table',
            name='total_table',
        ),
        migrations.RemoveField(
            model_name='table',
            name='total_table_reserved',
        ),
    ]
