# Generated by Django 4.1.3 on 2023-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0081_remove_table_table_total_empty_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalGuest',
            fields=[
                ('idguest', models.AutoField(primary_key=True, serialize=False)),
                ('guestNumber', models.IntegerField()),
            ],
        ),
    ]
